"""Build the submission zip and validate structure.

Layout produced:
    /bot.py            # shim — re-exports `decide` from src.bot
    /src/*.py          # real implementation
    /data/*            # blueprints (optional)

Usage:
    python tools/package.py --output submissions/v_final.zip [--strict]

The engine's authoritative validator lives at
`ext/fullhouse-engine/sandbox/validator.py`. Run it after this script for
the final word.
"""
import argparse
import sys
import zipfile
from pathlib import Path

# Scratch build: source the rescrubbed copy in this lane dir, NOT canonical src.
LANE = Path(__file__).resolve().parent
ROOT = LANE
MAX_BYTES = 250 * 1024 * 1024
MAX_DATA_BYTES = 200 * 1024 * 1024
MAX_BOT_PY_BYTES = 5 * 1024 * 1024

SHIM = '''"""bot.zip entry shim — real implementation lives in src/bot.py.

The engine validator AST-scans this file for a literal `def decide(...)` so
the function is defined explicitly here and forwards to the real impl.
This file is generated by tools/package.py; do not edit it in the source tree.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from src.bot import decide as _impl


def decide(game_state):
    return _impl(game_state)
'''


def build(output: Path, strict: bool = False) -> int:
    output.parent.mkdir(parents=True, exist_ok=True)
    src_dir = ROOT / "src"
    data_dir = ROOT / "data"

    if not (src_dir / "bot.py").exists():
        print("FAIL: src/bot.py missing")
        return 2

    data_size = 0
    if data_dir.exists():
        for f in data_dir.rglob("*"):
            if f.is_file():
                data_size += f.stat().st_size

    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as z:
        # Shim at archive root
        z.writestr("bot.py", SHIM)
        # All src/ files preserved under src/ in the archive
        for f in sorted(src_dir.rglob("*.py")):
            arc = Path("src") / f.relative_to(src_dir)
            z.write(f, arcname=str(arc))
        # data/ preserved under data/
        if data_dir.exists():
            for f in sorted(data_dir.rglob("*")):
                if f.is_file():
                    arc = Path("data") / f.relative_to(data_dir)
                    z.write(f, arcname=str(arc))

    size = output.stat().st_size
    print(f"built {output} ({size / (1024 * 1024):.2f} MB; data {data_size / (1024 * 1024):.2f} MB)")

    if strict:
        problems = []
        if size > MAX_BYTES:
            problems.append(f"archive {size} bytes > {MAX_BYTES} (250 MB)")
        if data_size > MAX_DATA_BYTES:
            problems.append(f"data/ {data_size} bytes > {MAX_DATA_BYTES} (200 MB)")
        with zipfile.ZipFile(output) as z:
            names = z.namelist()
            if "bot.py" not in names:
                problems.append("bot.py not at archive root")
            root_py = [n for n in names if "/" not in n and n.endswith(".py")]
            if root_py != ["bot.py"]:
                problems.append(f"unexpected .py at archive root: {root_py}")
            for n in names:
                if n.startswith("data/") and n.endswith(".py"):
                    problems.append(f".py inside data/: {n}")
            try:
                bot_info = z.getinfo("bot.py")
                if bot_info.file_size > MAX_BOT_PY_BYTES:
                    problems.append(f"bot.py {bot_info.file_size} > {MAX_BOT_PY_BYTES} (5 MB)")
            except KeyError:
                pass
        if problems:
            for p in problems:
                print(f"FAIL: {p}")
            return 3
    return 0


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--strict", action="store_true")
    args = p.parse_args()
    return build(args.output, args.strict)


if __name__ == "__main__":
    sys.exit(main())
