"""bot.zip entry shim — real implementation lives in src/bot.py.

The engine validator AST-scans this file for a literal `def decide(...)` so
the function is defined explicitly here and forwards to the real impl.
This file is generated by tools/package.py; do not edit it in the source tree.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from src.bot import decide as _impl


def decide(game_state):
    return _impl(game_state)
